apiVersion: v1
data:
  nginx.conf: "pid /tmp/nginx.pid;\nevents {\n}\n\nhttp {\n\n\tserver {\n\n\t\tlisten
    8080;\n\n\t\tlocation / {\n\t\t\troot /usr/share/nginx/html;\n\t\t\tindex index.html
    index.htm;\n\t\t}\n\n\t\tlocation /quote {\n\t\t\tproxy_pass http://quote-service/;\n\t\t}\n\t}\n\n\tupstream
    quote-service {\n\t\tserver phraseservice-server:3000;\n\t}\n\n}"
kind: ConfigMap
metadata:
  name: frontend-config-nginx
